# lan.conf - Network configuration for ipmi_sim

name "IPMI-SIM-SERVER"

set_working_mc 0x20

  startlan 1
    addr 0.0.0.0 623
    priv_limit admin

    allowed_auths_callback none md2 md5 straight
    allowed_auths_user none md2 md5 straight
    allowed_auths_operator none md2 md5 straight
    allowed_auths_admin none md2 md5 straight

    guid a123456789abcdefa123456789abcdef

    lan_config_program "/etc/ipmi/lancontrol eth0"
  endlan

  chassis_control "/tmp/ipmisim/bin/chassis_control.sh 0x20"

  # User 1 = anonymous (disabled), User 2 = ADMIN
  user 1 false ""        "test"  user     10       none md2 md5 straight
  user 2 true  "ADMIN"   "ADMIN" admin    10       none md2 md5 straight
